version: '3.8'

services:
  app:
    build: .
    container_name: icc_icf_scrapper
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=credentials/SA-thalescosendey.json
    command: ["python", "src/main.py"]
    restart: always
